version: '3.8'

services:
  app:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app_network

  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
